commonAnnotations:
  giantswarm.io/docs: https://docs.giantswarm.io/reference/cp-k8s-api/releases.release.giantswarm.io/
resources:
- v9.0.9
- v9.0.10
- v9.3.9
- v11.3.1
- v11.5.2
- v11.6.1
- v12.7.0
- v12.7.1
- v12.7.2
- v13.0.0
- v13.1.0
- v13.1.1
- v14.0.0
- v14.1.1
- v15.0.0-k8s120
transformers:
- releaseNotesTransformer.yaml
